### ISSUE TITLE
Grammar Error

### ISSUE THREAD

**Issue by Groonir** [enteraname74/SoulSearching#7]
Would it be possible to change the "musics" to "music" as the word's plural is the same as the singular version. 
Also "Personalization" is written as "Personalisation" in the settings tab

Thanks a lot for making this app as i found it very useful

**Comment by jsrockstaranks** [comment]
Personalization is correct spelling as per American English while Personalisation is in British English, so I think both are correct.

**Comment by enteraname74** [comment]
I will see which version to choose and correct spelling mistakes. This will be fixed in the next release of the application.

Thanks for using Soul Searching!

**Comment by Groonir** [comment]
> Personalization is correct spelling as per American English while Personalisation is in British English, so I think both are correct.

Since the app does not have a language option, it probably uses the locale. I am using a British English locale which is why i have made this issue

**Comment by enteraname74** [comment]
> > Personalization is correct spelling as per American English while Personalisation is in British English, so I think both are correct.
> 
> Since the app does not have a language option, it probably uses the locale. I am using a British English locale which is why i have made this issue

For now, Soul Searching has two supported languages, French (my primary language) and a default one which is English. The English version is used if the system doesn't use French. But it's true that, for the English version, it's not clear whether it's the Great Britain version or the American one.  

Currently, I will try to stick with the American version by default because some strings that are in the app use American English. However, for the future, I will let users choose their language in the settings of the app.

**Comment by Groonir** [comment]
Thanks for the clarification!

**Comment by enteraname74** [comment]
I fixed some grammar errors for the English version in the new release of the application. I changed the use of the word music to song, as I find it better for the application.
Let me know if it's all good for you.

**Comment by Groonir** [comment]
Yes it is. Thanks!
